version = 0

[packages]
[packages.base]

ghc = "9.10.1"
haskell_cabal_install = "3.14.1.0"
haskell_language_server = "2.9.0.0+ghc-9.10.1"
make = "4.4.1"
node = "21.6.2"
zlib = "1.3.1"

[shell]
[shell.env]

C_INCLUDE_PATH = [
    "${zlib}/include",
]

LIBRARY_PATH = [
    "${zlib}/lib",
]
