.PHONY: all
all : build prettier cabal_fmt ormolu weeder

.PHONY: clean
clean :
	./scripts/clean.sh

.PHONY: build
build : clean
	cabal build all --ghc-options='-Werror'

.PHONY: prettier
prettier :
	./scripts/prettier_check.sh

.PHONY: cabal_fmt
cabal_fmt : clean
	./scripts/cabal_fmt_check.sh

.PHONY: ormolu
ormolu : clean
	./scripts/ormolu_check.sh

.PHONY: weeder
weeder : build
	./scripts/weeder.sh
