name: devpacks-site

on:
  push:
    branches: "**"

defaults:
  run:
    shell: bash

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: install-devpacks
        run: |
          DEVPACKS_VERSION=0.8.0.3
          wget --no-verbose "https://mirror1.devpacks.org/packages/devpacks/devpacks-${DEVPACKS_VERSION}-linux-x86_64.tar.gz"
          tar -xvf "devpacks-${DEVPACKS_VERSION}-linux-x86_64.tar.gz"
          mv "devpacks-${DEVPACKS_VERSION}-linux-x86_64/bin/devpacks" /usr/local/bin
          devpacks --version

      - name: clean
        run: |
          ./scripts/clean.sh

      - name: build
        run: |
          ./scripts/build.sh

      - name: npm_install
        run: |
          ./scripts/npm_install.sh

      - name: prettier
        run: |
          ./scripts/prettier_check.sh

      - name: js_beautify
        run: |
          ./scripts/js_beautify_check.sh

      - name: cabal_fmt
        run: |
          ./scripts/cabal_fmt_check.sh

      - name: ormolu
        run: |
          ./scripts/ormolu_check.sh

      - name: weeder
        run: |
          ./scripts/weeder.sh
